language: node_js
node_js:
- '0.12'
before_script:
- npm install
script:
- npm test
deploy:
  provider: npm
  api_key:
    secure: ggdtt6+plZQfHmLwAad01WdMKs2yDLXbpvpXXdTOnI6YE81cVQUnmOqHMAJ/zghK43yNx8B7KRKZ3RrTNy+cNIxZEqeoKZHVuUQ4WoiSkrO8M9jCyTz57pdXzaCQ4GsrgXUuDq4XyVPDdWCvyDefxcbkCNCyg90sTpealX8Ew7u7IhX/g6mpho0x5lJHVgZ0GjxRwpHJA1aAsStuqYamCpLEK9qPApu72Qtvc76d98z+b9YqTO12cXvV3UnxrCMirGoTOkV4+xkoV9eCelh5qks3XqpkHRRl8ltfb+fsG15jcFKmuGmccz2Ixt0Y48BOYTJqTPaUbpb3NtJMsxlSqRm6QYrS5OJKEnqM1SoHPeAa0ftB8fLRdUJIJrqbcDTthm3W0JIgzrN6yakoH5Ml/gZTi1Rg9AaYDKzfOIGNKabG230L5zDTXFKo1arhQ+4bL/1GVhGtj9VKUYIKZRgiGypCxQNYd5+KiJdDRLWdJQmDwqCV18/jr+hm4eVuoeUAx6kSuF9xtLCUGV+QM+h3OSwEawVdaHJWxTZukMvJkjZOqH4FdzesOt7DYZbFErJydJfALSBOOHBnt38IvQxshPdZNyA0J7K5rdWTyV6Ec8Y5nZn9oA4EYM5LEHsULL4DV+pZr9frAyB3XEGzoTcaETQuY0PzFt38VTkUGhJa6c4=
  email:
    secure: nxTfwz8TpyyQhrvkw2BGyG+FG54sMZl+8aVRF+Nz0JjA7Y+/kmlZY7IFw4yzJqqKHtV/nPE+qfNQlnehp8QDCyw21fF/DjR+xFN6+hLOjtqhDaElfG7BFekCfck/bIz/eT+d3r01kCVJBLbzNvNICVWRMV0O0lLgAih6tvfgIANnoq43G4ZYbsGHjux+niGl4EcnfPRHR9qjghE/dxy+TAprG8RLGvxbIOstLMdON9E8PUmIu64rvjH32Srqoj1wNLo71P1bTCfBxpGvzyONxpzlJl2Net94qe4LVfhY+i+BI0UHfEIUwt0yYJhJ0j0Ppkjvl9zdwnTtOfgdBm4lbf7Sw/vLAOX0xB2zULz7ysVXSSz2Njh/tXLajv7ffVaISpMCc7ONDttEegV9xIrH2UX5XTpRH0NcWyALwcYeTmHsvVnLLiD86qso73jQxn/COuMxKncbgvpAPKTl7sNOE1bbAr3c4sx1/05j+W3sTvM7QhdLeHwEFoZikIFqG0gdM0T2FDJUKJApAFyYYnvmwHOJ5PucISrUda77K9uJX7a0rozNyIfrU2R61Meck7eJQGWQr8cASDPFyJt74j5PNSeyUEwgIxl9ndZ3iw+t6BV3TwAHSh5umYCqjWH1ZL5BcP+fWQxyeSAEaQEndURybDyaUxHlXD6ez2sTgoeMUrs=
