version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "Install dependencies"
      - npm ci
  build:
    on-failure: ABORT
    commands:
      - echo "Testing"
      - npm test
